/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSplatRouteImport } from './routes/_shell/$'
import { Route as ShellAccountRouteImport } from './routes/_shell/account'
import { Route as ShellUsersRouteImport } from './routes/_shell/users'
import { Route as SetupIndexRouteImport } from './routes/setup/index'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSplatRoute = ShellSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAccountRoute = ShellAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => ShellRoute,
} as any)
const ShellUsersRoute = ShellUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellRoute,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/$': typeof ShellSplatRoute
  '/account': typeof ShellAccountRoute
  '/users': typeof ShellUsersRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/$': typeof ShellSplatRoute
  '/account': typeof ShellAccountRoute
  '/users': typeof ShellUsersRoute
  '/': typeof ShellIndexRoute
  '/setup': typeof SetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/$': typeof ShellSplatRoute
  '/_shell/account': typeof ShellAccountRoute
  '/_shell/users': typeof ShellUsersRoute
  '/_shell/': typeof ShellIndexRoute
  '/setup/': typeof SetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/$' | '/account' | '/users' | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/$' | '/account' | '/users' | '/' | '/setup'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/$'
    | '/_shell/account'
    | '/_shell/users'
    | '/_shell/'
    | '/setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/$': {
      id: '/_shell/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof ShellSplatRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/account': {
      id: '/_shell/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof ShellAccountRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/users': {
      id: '/_shell/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof ShellUsersRouteImport
      parentRoute: typeof ShellRoute
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ShellRouteChildren {
  ShellSplatRoute: typeof ShellSplatRoute
  ShellAccountRoute: typeof ShellAccountRoute
  ShellUsersRoute: typeof ShellUsersRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSplatRoute: ShellSplatRoute,
  ShellAccountRoute: ShellAccountRoute,
  ShellUsersRoute: ShellUsersRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
