/**
 * How the test fixtures are made.
 *
 * The committed files under this directory are assembled here, byte by byte,
 * from nothing but this module: an MP3 with an ID3v2.3 tag and an embedded
 * cover, the same MP3 with no tag at all, a FLAC with a Vorbis comment block
 * and a PICTURE block, two M4As that differ only in whether `moov` comes
 * before or after `mdat`, the cover image itself, and an `.m3u` that points at
 * four of them plus a line that matches nothing.
 *
 * `pnpm --filter @stratosonic/server fixtures` writes what this module returns
 * to disk; a test calls the same functions and compares them with the committed
 * bytes, so the files can always be regenerated byte for byte. The generator
 * probes for `ffmpeg` and reports what it finds, but does not use it: an
 * encoder's output varies with its version and build, and these fixtures have
 * to be reproducible by anyone.
 *
 * The audio is silence: zeroed MPEG frames, a stub FLAC frame and an empty
 * `mdat`. Everything a parser reads, though, is real - the ID3v2.3 frames, the
 * FLAC block chain, and an MP4 movie box carrying a full `trak` with `mdhd`,
 * `stsd`/`mp4a` and an `esds`, so a parser that wants the sample rate and the
 * bit rate from the track rather than from `mvhd` finds them. The sample
 * tables are empty, so the files describe themselves correctly but decode to
 * nothing.
 *
 * Every expectation these files carry - tags, durations, bit rates, cover
 * types, which album has a cover, which playlist lines match - is written into
 * `manifest.json` by the same run, so the tests that read the fixtures never
 * restate them.
 */

/** A file as it is committed under this directory. */
export interface FixtureFile {
  readonly name: string;
  readonly bytes: Uint8Array;
}

export type FixtureSuffix = "mp3" | "flac" | "m4a";

/** The tags a fixture carries, where it carries any. */
export interface FixtureTags {
  readonly title: string;
  readonly artist: string;
  readonly albumArtist: string;
  readonly album: string;
  readonly trackNumber: number;
  readonly trackCount: number;
  readonly discNumber: number;
  readonly discCount: number;
  readonly year: number;
  readonly genre: string;
}

/** An embedded or stored cover image. */
export interface FixtureCover {
  readonly mimeType: string;
  readonly size: number;
  readonly width: number;
  readonly height: number;
}

/** What a fixture's bytes say, for the tests that read them. */
export interface FixtureTrack {
  /** File name under `test/fixtures`. */
  readonly file: string;
  /** Where the seed helper puts it in the R2 bucket. */
  readonly r2Key: string;
  readonly size: number;
  readonly suffix: FixtureSuffix;
  readonly contentType: string;
  readonly container: {
    readonly tagFormat: "id3v2.3" | "vorbis-comment" | "mp4-ilst" | "none";
    /** MP4 only: whether the metadata sits at the front of the file. */
    readonly moovBeforeMdat?: boolean;
  };
  /** Null when the file carries no tags at all. */
  readonly tags: FixtureTags | null;
  /**
   * What the R2 key alone says, which is what the scanner must fall back to
   * when a tag is missing: `albumArtist/album/title.suffix`.
   */
  readonly pathFallback: {
    readonly albumArtist: string;
    readonly album: string;
    readonly title: string;
  };
  readonly duration: {
    readonly seconds: number;
    readonly toleranceSeconds: number;
    /** Which of the three rules in #9 yields it. */
    readonly source: "cbr-estimate" | "streaminfo" | "mvhd";
  };
  readonly bitRate: {
    readonly kbps: number;
    readonly source: "frame-header" | "esds" | "size-and-duration";
  };
  readonly cover: FixtureCover | null;
}

/** An album the fixtures add up to, as a completed scan would record it. */
export interface FixtureAlbum {
  readonly name: string;
  readonly albumArtist: string;
  readonly year: number | null;
  readonly genre: string | null;
  /** Its tracks, by fixture file name, in the order the fixtures list them. */
  readonly trackFiles: readonly string[];
  /**
   * Whether any of its tracks carries a cover. The one album whose tracks have
   * none exists so the read endpoints can prove they omit `coverArt` rather
   * than emitting an id that resolves to nothing.
   */
  readonly hasCover: boolean;
}

/** One line of the `.m3u`, and what the importer should make of it. */
export interface FixturePlaylistLine {
  readonly text: string;
  /** The R2 key the line resolves to, or null for a comment or blank line. */
  readonly resolvesTo: string | null;
  readonly matchesATrack: boolean;
  /**
   * Whether the line ends CRLF rather than LF. An importer that does not strip
   * the carriage return looks up a key that ends in one and finds nothing.
   */
  readonly carriageReturn: boolean;
}

export interface FixturePlaylist {
  readonly file: string;
  readonly r2Key: string;
  /** The playlist's name: the file name without its extension. */
  readonly name: string;
  readonly size: number;
  readonly lines: readonly FixturePlaylistLine[];
  /** The tracks it should import, in order. */
  readonly trackKeys: readonly string[];
  readonly unmatchedLineCount: number;
}

export interface FixturesManifest {
  readonly generator: {
    readonly command: string;
    readonly source: string;
    readonly engine: "programmatic";
  };
  /** The cover image every tagged fixture embeds, also committed on its own. */
  readonly cover: FixtureCover & { readonly file: string };
  readonly tracks: readonly FixtureTrack[];
  readonly albums: readonly FixtureAlbum[];
  readonly playlist: FixturePlaylist;
}

/** Everything under this directory, and what it means. */
export interface BuiltFixtures {
  readonly files: readonly FixtureFile[];
  readonly manifest: FixturesManifest;
}

const COVER_FILE = "cover.png";
const COVER_WIDTH = 1;
const COVER_HEIGHT = 1;

/** MPEG-1 Layer III, 128 kbps, 44.1 kHz: the MP3 fixtures' one frame shape. */
const MP3_BIT_RATE = 128;
const MP3_SAMPLE_RATE = 44_100;
const MP3_FRAME_SIZE = Math.floor((144 * MP3_BIT_RATE * 1000) / MP3_SAMPLE_RATE);
const MP3_FRAME_COUNT = 8;

const FLAC_SAMPLE_RATE = 44_100;
const FLAC_TOTAL_SAMPLES = 44_100;
const FLAC_STUB_FRAME_SIZE = 2048;

/**
 * The M4A fixtures describe a real, if tiny, AAC stream: 32 frames of 1024
 * samples at 44.1 kHz, each 64 bytes, which is exactly the `mdat` they carry.
 * Keeping the sample table, the media header and the decoder configuration
 * agreeing with one another is what lets a parser report a duration and a bit
 * rate at all - music-metadata derives the bit rate from the sample sizes, not
 * from `esds`.
 */
const MP4_TIMESCALE = 1000;
const MP4_SAMPLE_RATE = 44_100;
const MP4_SAMPLES_PER_FRAME = 1024;
const MP4_FRAME_COUNT = 32;
const MP4_FRAME_SIZE = 64;
const MP4_MEDIA_DURATION = MP4_SAMPLES_PER_FRAME * MP4_FRAME_COUNT;
const MP4_SECONDS = MP4_MEDIA_DURATION / MP4_SAMPLE_RATE;
const MP4_DURATION_UNITS = Math.round(MP4_SECONDS * MP4_TIMESCALE);
const MP4_MDAT_SIZE = MP4_FRAME_SIZE * MP4_FRAME_COUNT;
const MP4_BITS_PER_SECOND = Math.round((MP4_MDAT_SIZE * 8) / MP4_SECONDS);

/** Builds every fixture file together with the manifest that describes them. */
export function buildFixtures(): BuiltFixtures {
  const cover = pngCover();

  const tracks = [
    mp3Fixture(cover),
    flacFixture(cover),
    mp4Fixture({
      file: "front-loaded.m4a",
      r2Key: "Mute Ensemble/Faststart Sessions/01 Front Loaded.m4a",
      moovBeforeMdat: true,
      tags: {
        title: "Front Loaded",
        artist: "Mute Ensemble",
        albumArtist: "Mute Ensemble",
        album: "Faststart Sessions",
        trackNumber: 1,
        trackCount: 3,
        discNumber: 1,
        discCount: 1,
        year: 2019,
        genre: "Ambient",
      },
      cover,
    }),
    mp4Fixture({
      file: "tail-loaded.m4a",
      r2Key: "Mute Ensemble/Trailing Sessions/01 Tail Loaded.m4a",
      moovBeforeMdat: false,
      tags: {
        title: "Tail Loaded",
        artist: "Mute Ensemble",
        albumArtist: "Mute Ensemble",
        album: "Trailing Sessions",
        trackNumber: 1,
        trackCount: 3,
        discNumber: 1,
        discCount: 1,
        year: 2019,
        genre: "Ambient",
      },
      cover,
    }),
    untaggedMp3Fixture(),
  ];
  const playlist = m3uFixture(tracks);

  return {
    files: [
      ...tracks.map((track) => track.fixture),
      { name: COVER_FILE, bytes: cover },
      playlist.fixture,
    ],
    manifest: {
      generator: {
        command: "pnpm --filter @stratosonic/server fixtures",
        source: "apps/server/test/fixtures/build.ts",
        engine: "programmatic",
      },
      cover: {
        file: COVER_FILE,
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
      tracks: tracks.map((track) => track.track),
      albums: albumsOf(tracks.map((track) => track.track)),
      playlist: playlist.playlist,
    },
  };
}

interface BuiltTrack {
  readonly fixture: FixtureFile;
  readonly track: FixtureTrack;
}

/**
 * The albums the tracks add up to, grouped the way the scanner groups them:
 * by album artist, album name and year, taking the path fallback where a track
 * has no tags.
 */
function albumsOf(tracks: readonly FixtureTrack[]): FixtureAlbum[] {
  const albums = new Map<string, FixtureAlbum & { trackFiles: string[] }>();

  for (const track of tracks) {
    const name = track.tags?.album ?? track.pathFallback.album;
    const albumArtist = track.tags?.albumArtist ?? track.pathFallback.albumArtist;
    const year = track.tags?.year ?? null;
    const key = `${albumArtist}|${name}|${year}`;
    const existing = albums.get(key);

    if (existing) {
      existing.trackFiles.push(track.file);
      continue;
    }

    albums.set(key, {
      name,
      albumArtist,
      year,
      genre: track.tags?.genre ?? null,
      trackFiles: [track.file],
      hasCover: track.cover !== null,
    });
  }

  return [...albums.values()].map((album) => ({
    ...album,
    hasCover: album.trackFiles.some(
      (file) => tracks.find((track) => track.file === file)?.cover !== null,
    ),
  }));
}

/** What an R2 key says on its own: `albumArtist/album/title.suffix`. */
function pathFallbackOf(r2Key: string): FixtureTrack["pathFallback"] {
  const segments = r2Key.split("/");

  return {
    albumArtist: segments.at(-3) ?? "",
    album: segments.at(-2) ?? "",
    title: (segments.at(-1) ?? "").replace(/\.[^.]+$/, ""),
  };
}

/* ------------------------------------------------------------------ MP3 -- */

/** The zeroed MPEG-1 Layer III frames both MP3 fixtures end with. */
function mp3Frames(): Uint8Array {
  const audio = new Uint8Array(MP3_FRAME_SIZE * MP3_FRAME_COUNT);

  // MPEG-1 Layer III, 128 kbps, 44.1 kHz, stereo, no padding. Nothing decodes
  // the frames; their count and the header are what a parser reads.
  for (let frame = 0; frame < MP3_FRAME_COUNT; frame++) {
    audio.set(Uint8Array.of(0xff, 0xfb, 0x90, 0x00), frame * MP3_FRAME_SIZE);
  }

  return audio;
}

/**
 * The duration of the MP3 fixtures. There is no Xing or Info frame, so it is
 * the CBR estimate over the audio bytes, which agrees with
 * frames x 1152 / 44100 to a millisecond.
 */
function mp3Seconds(audio: Uint8Array): number {
  return round((audio.length * 8) / (MP3_BIT_RATE * 1000), 3);
}

function mp3Fixture(cover: Uint8Array): BuiltTrack {
  const tags: FixtureTags = {
    title: "Silent Track",
    artist: "Silent Artist",
    albumArtist: "Silent Artist",
    album: "Quiet Album",
    trackNumber: 1,
    trackCount: 2,
    discNumber: 1,
    discCount: 1,
    year: 2001,
    genre: "Electronic",
  };

  const frames = concat(
    id3TextFrame("TIT2", tags.title),
    id3TextFrame("TPE1", tags.artist),
    id3TextFrame("TPE2", tags.albumArtist),
    id3TextFrame("TALB", tags.album),
    id3TextFrame("TRCK", `${tags.trackNumber}/${tags.trackCount}`),
    id3TextFrame("TPOS", `${tags.discNumber}/${tags.discCount}`),
    id3TextFrame("TYER", String(tags.year)),
    id3TextFrame("TCON", tags.genre),
    id3Frame(
      "APIC",
      concat(
        Uint8Array.of(0x00),
        latin1("image/png"),
        Uint8Array.of(0x00),
        // Picture type 3: the front cover.
        Uint8Array.of(0x03),
        Uint8Array.of(0x00),
        cover,
      ),
    ),
  );

  // "ID3", version 2.3.0, no flags, then the tag size as a syncsafe integer.
  const header = concat(latin1("ID3"), Uint8Array.of(0x03, 0x00, 0x00), syncsafe(frames.length));
  const audio = mp3Frames();
  const bytes = concat(header, frames, audio);
  const r2Key = "Silent Artist/Quiet Album/01 Silent Track.mp3";

  return {
    fixture: { name: "silent-track.mp3", bytes },
    track: {
      file: "silent-track.mp3",
      r2Key,
      size: bytes.length,
      suffix: "mp3",
      contentType: "audio/mpeg",
      container: { tagFormat: "id3v2.3" },
      tags,
      pathFallback: pathFallbackOf(r2Key),
      duration: {
        seconds: mp3Seconds(audio),
        toleranceSeconds: 0.05,
        source: "cbr-estimate",
      },
      bitRate: { kbps: MP3_BIT_RATE, source: "frame-header" },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

/**
 * The same MPEG frames with no tag in front of them, so the scanner has
 * something whose artist, album and title can only come from its R2 key, and
 * an album with no cover at all.
 */
function untaggedMp3Fixture(): BuiltTrack {
  const audio = mp3Frames();
  const r2Key = "Fallback Artist/Fallback Album/01 Untagged.mp3";

  return {
    fixture: { name: "untagged.mp3", bytes: audio },
    track: {
      file: "untagged.mp3",
      r2Key,
      size: audio.length,
      suffix: "mp3",
      contentType: "audio/mpeg",
      container: { tagFormat: "none" },
      tags: null,
      pathFallback: pathFallbackOf(r2Key),
      duration: {
        seconds: mp3Seconds(audio),
        toleranceSeconds: 0.05,
        source: "cbr-estimate",
      },
      bitRate: { kbps: MP3_BIT_RATE, source: "frame-header" },
      cover: null,
    },
  };
}

/** An ID3v2.3 frame: id, size (plain big-endian in 2.3), two flag bytes. */
function id3Frame(id: string, body: Uint8Array): Uint8Array {
  return concat(latin1(id), u32be(body.length), Uint8Array.of(0x00, 0x00), body);
}

/** A text frame, in ISO-8859-1 as encoding byte 0 declares. */
function id3TextFrame(id: string, text: string): Uint8Array {
  return id3Frame(id, concat(Uint8Array.of(0x00), latin1(text)));
}

/** A 28-bit integer spread over four bytes, seven bits each. */
function syncsafe(value: number): Uint8Array {
  return Uint8Array.of(
    (value >> 21) & 0x7f,
    (value >> 14) & 0x7f,
    (value >> 7) & 0x7f,
    value & 0x7f,
  );
}

/* ----------------------------------------------------------------- FLAC -- */

function flacFixture(cover: Uint8Array): BuiltTrack {
  const tags: FixtureTags = {
    title: "Hushed Interlude",
    // The track artist differs from the album artist on purpose: the library
    // groups by album artist, and something has to prove it.
    artist: "Silent Artist feat. Echo",
    albumArtist: "Silent Artist",
    album: "Quiet Album",
    trackNumber: 2,
    trackCount: 2,
    discNumber: 1,
    discCount: 1,
    year: 2001,
    genre: "Electronic",
  };

  const streamInfo = new Uint8Array(34);
  const view = new DataView(streamInfo.buffer);
  // Minimum and maximum block size, then minimum and maximum frame size (both
  // zero, meaning "unknown").
  view.setUint16(0, 4096);
  view.setUint16(2, 4096);
  // Bits 20 (sample rate), 3 (channels - 1), 5 (bits per sample - 1) and 36
  // (total samples) are packed into the eight bytes from offset 10.
  const packed =
    (BigInt(FLAC_SAMPLE_RATE) << 44n) | (1n << 41n) | (15n << 36n) | BigInt(FLAC_TOTAL_SAMPLES);
  view.setBigUint64(10, packed);
  // The last 16 bytes are the MD5 of the unencoded audio, which may be zero
  // when it is unknown.

  // Both totals are written: a comment block that gives TRACKNUMBER without
  // TRACKTOTAL leaves a parser reporting "2 of null", and the manifest would
  // be promising a count the bytes do not carry.
  const comments = [
    `TITLE=${tags.title}`,
    `ARTIST=${tags.artist}`,
    `ALBUMARTIST=${tags.albumArtist}`,
    `ALBUM=${tags.album}`,
    `TRACKNUMBER=${tags.trackNumber}`,
    `TRACKTOTAL=${tags.trackCount}`,
    `DISCNUMBER=${tags.discNumber}`,
    `DISCTOTAL=${tags.discCount}`,
    `DATE=${tags.year}`,
    `GENRE=${tags.genre}`,
  ];
  const vendor = utf8("stratosonic fixtures");
  const vorbisComment = concat(
    u32le(vendor.length),
    vendor,
    u32le(comments.length),
    ...comments.map((comment) => {
      const encoded = utf8(comment);
      return concat(u32le(encoded.length), encoded);
    }),
  );

  const mimeType = latin1("image/png");
  const description = utf8("front cover");
  const picture = concat(
    u32be(3),
    u32be(mimeType.length),
    mimeType,
    u32be(description.length),
    description,
    u32be(COVER_WIDTH),
    u32be(COVER_HEIGHT),
    // 24-bit colour, not a palette.
    u32be(24),
    u32be(0),
    u32be(cover.length),
    cover,
  );

  // A stub frame, so the file does not end on its metadata. It is not decodable
  // and nothing reads it: the duration comes from STREAMINFO.
  const frame = new Uint8Array(FLAC_STUB_FRAME_SIZE);
  frame.set(Uint8Array.of(0xff, 0xf8, 0x69, 0x18, 0x00));

  const bytes = concat(
    latin1("fLaC"),
    flacBlock(0, streamInfo, false),
    flacBlock(4, vorbisComment, false),
    flacBlock(6, picture, true),
    frame,
  );
  const seconds = FLAC_TOTAL_SAMPLES / FLAC_SAMPLE_RATE;
  const r2Key = "Silent Artist/Quiet Album/02 Hushed Interlude.flac";

  return {
    fixture: { name: "hushed-interlude.flac", bytes },
    track: {
      file: "hushed-interlude.flac",
      r2Key,
      size: bytes.length,
      suffix: "flac",
      contentType: "audio/flac",
      container: { tagFormat: "vorbis-comment" },
      tags,
      pathFallback: pathFallbackOf(r2Key),
      duration: { seconds, toleranceSeconds: 0.01, source: "streaminfo" },
      // FLAC states no bit rate, so it is the stream's own - the audio bytes
      // after the metadata blocks, which is what both TagLib and
      // music-metadata divide by the duration. These bytes are not a real
      // encoding, so the number is small, but the rule is the rule.
      bitRate: {
        kbps: round((FLAC_STUB_FRAME_SIZE * 8) / 1000 / seconds),
        source: "size-and-duration",
      },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

/** A metadata block: one byte of "last block" flag and type, then a 24-bit length. */
function flacBlock(type: number, body: Uint8Array, last: boolean): Uint8Array {
  return concat(Uint8Array.of((last ? 0x80 : 0x00) | type), u24be(body.length), body);
}

/* ------------------------------------------------------------------ MP4 -- */

interface Mp4Spec {
  readonly file: string;
  readonly r2Key: string;
  readonly moovBeforeMdat: boolean;
  readonly tags: FixtureTags;
  readonly cover: Uint8Array;
}

function mp4Fixture(spec: Mp4Spec): BuiltTrack {
  const { tags, cover } = spec;

  const ftyp = atom(
    "ftyp",
    concat(latin1("M4A "), u32be(0x200), latin1("M4A "), latin1("mp42"), latin1("isom")),
  );

  const mvhd = atom(
    "mvhd",
    concat(
      // Version 0, no flags; created and modified at the epoch.
      u32be(0),
      u32be(0),
      u32be(0),
      u32be(MP4_TIMESCALE),
      u32be(MP4_DURATION_UNITS),
      // Rate 1.0, volume 1.0, then the reserved words, the unity matrix and
      // the predefined block, all as the specification fixes them.
      u32be(0x00010000),
      Uint8Array.of(0x01, 0x00),
      new Uint8Array(10),
      unityMatrix(),
      new Uint8Array(24),
      u32be(2),
    ),
  );

  const ilst = atom(
    "ilst",
    concat(
      itunesText("\u00a9nam", tags.title),
      itunesText("\u00a9ART", tags.artist),
      itunesText("aART", tags.albumArtist),
      itunesText("\u00a9alb", tags.album),
      itunesText("\u00a9day", String(tags.year)),
      itunesText("\u00a9gen", tags.genre),
      itunesNumberPair("trkn", tags.trackNumber, tags.trackCount),
      itunesNumberPair("disk", tags.discNumber, tags.discCount),
      // Data type 14 says the picture is a PNG.
      itunesItem("covr", 14, cover),
    ),
  );

  // `meta` is a full box: four bytes of version and flags before its children.
  const meta = atom("meta", concat(u32be(0), metadataHandler(), ilst));
  const moov = atom("moov", concat(mvhd, soundTrack(), atom("udta", meta)));
  const mdat = atom("mdat", new Uint8Array(MP4_MDAT_SIZE));

  const bytes = spec.moovBeforeMdat ? concat(ftyp, moov, mdat) : concat(ftyp, mdat, moov);
  const seconds = MP4_DURATION_UNITS / MP4_TIMESCALE;
  const r2Key = spec.r2Key;

  return {
    fixture: { name: spec.file, bytes },
    track: {
      file: spec.file,
      r2Key,
      size: bytes.length,
      suffix: "m4a",
      contentType: "audio/mp4",
      container: { tagFormat: "mp4-ilst", moovBeforeMdat: spec.moovBeforeMdat },
      tags,
      pathFallback: pathFallbackOf(r2Key),
      duration: { seconds, toleranceSeconds: 0.01, source: "mvhd" },
      // The sample table and the decoder configuration agree on this, so a
      // parser reaches it either way.
      bitRate: { kbps: round(MP4_BITS_PER_SECOND / 1000), source: "size-and-duration" },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

/**
 * The audio track: enough of one that a parser reading `trak` rather than
 * `mvhd` still finds the duration, the sample rate and the bit rate. The
 * sample tables are empty - there are no samples to describe - which is why
 * the files parse but do not play.
 */
function soundTrack(): Uint8Array {
  const tkhd = atom(
    "tkhd",
    concat(
      // Version 0; flags 7: enabled, in the movie, in the preview.
      u32be(0x00000007),
      u32be(0),
      u32be(0),
      u32be(1),
      u32be(0),
      // The track's duration is counted in the movie's timescale here.
      u32be(MP4_DURATION_UNITS),
      new Uint8Array(8),
      u16be(0),
      u16be(1),
      // Full volume, as an audio track carries.
      u16be(0x0100),
      u16be(0),
      unityMatrix(),
      // An audio track has no width or height.
      u32be(0),
      u32be(0),
    ),
  );

  const mdhd = atom(
    "mdhd",
    concat(
      u32be(0),
      u32be(0),
      u32be(0),
      // Inside the media, time is counted in samples.
      u32be(MP4_SAMPLE_RATE),
      u32be(MP4_MEDIA_DURATION),
      // Language "und", packed five bits per letter.
      u16be(0x55c4),
      u16be(0),
    ),
  );

  const hdlr = atom(
    "hdlr",
    concat(
      u32be(0),
      u32be(0),
      latin1("soun"),
      new Uint8Array(12),
      latin1("SoundHandler"),
      Uint8Array.of(0x00),
    ),
  );

  const smhd = atom("smhd", concat(u32be(0), u16be(0), u16be(0)));
  // One data reference, flagged self-contained: the samples are in this file.
  const dinf = atom("dinf", atom("dref", concat(u32be(0), u32be(1), atom("url ", u32be(1)))));

  const mp4a = atom(
    "mp4a",
    concat(
      new Uint8Array(6),
      // The data reference above.
      u16be(1),
      new Uint8Array(8),
      u16be(2),
      u16be(16),
      u16be(0),
      u16be(0),
      // The sample rate as 16.16 fixed point.
      u32be(MP4_SAMPLE_RATE * 0x10000),
      elementaryStreamDescriptor(),
    ),
  );

  const stbl = atom(
    "stbl",
    concat(
      atom("stsd", concat(u32be(0), u32be(1), mp4a)),
      // One run of frames, all the same length, and all the same size.
      atom(
        "stts",
        concat(u32be(0), u32be(1), u32be(MP4_FRAME_COUNT), u32be(MP4_SAMPLES_PER_FRAME)),
      ),
      atom("stsc", concat(u32be(0), u32be(0))),
      // Each frame's size is listed rather than declared once: a parser that
      // adds the table up is how the bit rate is arrived at.
      atom(
        "stsz",
        concat(
          u32be(0),
          u32be(0),
          u32be(MP4_FRAME_COUNT),
          ...Array.from({ length: MP4_FRAME_COUNT }, () => u32be(MP4_FRAME_SIZE)),
        ),
      ),
      atom("stco", concat(u32be(0), u32be(0))),
    ),
  );

  return atom(
    "trak",
    concat(tkhd, atom("mdia", concat(mdhd, hdlr, atom("minf", concat(smhd, dinf, stbl))))),
  );
}

/**
 * The `esds` box: an MPEG-4 elementary stream descriptor saying the stream is
 * AAC-LC at 44.1 kHz in stereo, and what it costs per second - the same
 * number the sample table implies, so the two cannot disagree.
 */
function elementaryStreamDescriptor(): Uint8Array {
  const bitsPerSecond = MP4_BITS_PER_SECOND;
  // AudioSpecificConfig: object type 2 (AAC-LC), frequency index 4 (44.1 kHz),
  // two channels.
  const decoderSpecific = descriptor(0x05, Uint8Array.of(0x12, 0x10));
  const decoderConfig = descriptor(
    0x04,
    concat(
      // MPEG-4 audio, of stream type audio.
      Uint8Array.of(0x40, 0x15),
      u24be(0),
      u32be(bitsPerSecond),
      u32be(bitsPerSecond),
      decoderSpecific,
    ),
  );
  const sync = descriptor(0x06, Uint8Array.of(0x02));
  const stream = descriptor(0x03, concat(u16be(1), Uint8Array.of(0x00), decoderConfig, sync));

  return atom("esds", concat(u32be(0), stream));
}

/** A tag byte, a length, and the descriptor's body. */
function descriptor(tag: number, body: Uint8Array): Uint8Array {
  if (body.length > 0x7f) {
    throw new Error("a fixture descriptor never needs a multi-byte length");
  }

  return concat(Uint8Array.of(tag, body.length), body);
}

/** The handler that says `meta` holds iTunes-style metadata. */
function metadataHandler(): Uint8Array {
  return atom(
    "hdlr",
    concat(u32be(0), u32be(0), latin1("mdir"), latin1("appl"), new Uint8Array(8)),
  );
}

function atom(type: string, body: Uint8Array): Uint8Array {
  return concat(u32be(body.length + 8), latin1(type), body);
}

/** An `ilst` entry: a named atom wrapping one `data` atom. */
function itunesItem(name: string, dataType: number, value: Uint8Array): Uint8Array {
  return atom(name, atom("data", concat(u32be(dataType), u32be(0), value)));
}

/** Data type 1: UTF-8 text. */
function itunesText(name: string, text: string): Uint8Array {
  return itunesItem(name, 1, utf8(text));
}

/** Data type 0: `trkn` and `disk` hold their two numbers as binary. */
function itunesNumberPair(name: string, number: number, total: number): Uint8Array {
  return itunesItem(name, 0, concat(u16be(0), u16be(number), u16be(total), u16be(0)));
}

function unityMatrix(): Uint8Array {
  return concat(
    u32be(0x00010000),
    u32be(0),
    u32be(0),
    u32be(0),
    u32be(0x00010000),
    u32be(0),
    u32be(0),
    u32be(0),
    u32be(0x40000000),
  );
}

/* ------------------------------------------------------------------ m3u -- */

interface BuiltPlaylist {
  readonly fixture: FixtureFile;
  readonly playlist: FixturePlaylist;
}

function m3uFixture(tracks: readonly BuiltTrack[]): BuiltPlaylist {
  const named = (file: string) => {
    const track = tracks.find((candidate) => candidate.track.file === file);
    if (!track) {
      throw new Error(`the playlist fixture needs ${file}`);
    }

    return track.track;
  };

  const mp3 = named("silent-track.mp3");
  const flac = named("hushed-interlude.flac");
  const front = named("front-loaded.m4a");
  const untagged = named("untagged.mp3");
  const missing = "Missing Artist/Missing Album/Nowhere.mp3";

  // The playlist lives in a directory of its own, so a line has to be resolved
  // against `playlists/` before it names an R2 key. One line is relative, one
  // is absolute, one ends CRLF the way an editor on Windows leaves it, one
  // names a track that is not in the bucket, and one fixture track is
  // deliberately absent from the file.
  const lines: FixturePlaylistLine[] = [
    { text: "#EXTM3U", resolvesTo: null, matchesATrack: false, carriageReturn: false },
    {
      text: `#EXTINF:1,${mp3.tags?.artist} - ${mp3.tags?.title}`,
      resolvesTo: null,
      matchesATrack: false,
      carriageReturn: false,
    },
    {
      text: `../${mp3.r2Key}`,
      resolvesTo: mp3.r2Key,
      matchesATrack: true,
      carriageReturn: false,
    },
    {
      text: `/${front.r2Key}`,
      resolvesTo: front.r2Key,
      matchesATrack: true,
      carriageReturn: false,
    },
    {
      text: `../${untagged.r2Key}`,
      resolvesTo: untagged.r2Key,
      matchesATrack: true,
      carriageReturn: true,
    },
    { text: "", resolvesTo: null, matchesATrack: false, carriageReturn: false },
    {
      text: `../${missing}`,
      resolvesTo: missing,
      matchesATrack: false,
      carriageReturn: false,
    },
    {
      text: `../${flac.r2Key}`,
      resolvesTo: flac.r2Key,
      matchesATrack: true,
      carriageReturn: false,
    },
  ];

  const bytes = utf8(
    lines.map((line) => line.text + (line.carriageReturn ? "\r\n" : "\n")).join(""),
  );

  return {
    fixture: { name: "favourites.m3u", bytes },
    playlist: {
      file: "favourites.m3u",
      r2Key: "playlists/favourites.m3u",
      name: "favourites",
      size: bytes.length,
      lines,
      trackKeys: lines
        .filter((line) => line.matchesATrack)
        .map((line) => line.resolvesTo as string),
      unmatchedLineCount: 1,
    },
  };
}

/* ---------------------------------------------------------------- cover -- */

/**
 * A one-pixel PNG. It is built rather than pasted in so its checksums are right
 * by construction: the image is small but real, and the cover path treats it as
 * it would any other.
 */
function pngCover(): Uint8Array {
  const ihdr = concat(
    u32be(COVER_WIDTH),
    u32be(COVER_HEIGHT),
    // Eight bits per sample, colour type 2 (RGB), no compression, filter or
    // interlacing beyond the defaults.
    Uint8Array.of(8, 2, 0, 0, 0),
  );
  // One scanline: the filter byte, then one grey pixel.
  const raw = Uint8Array.of(0x00, 0x30, 0x30, 0x30);

  return concat(
    Uint8Array.of(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", zlibStored(raw)),
    pngChunk("IEND", new Uint8Array(0)),
  );
}

function pngChunk(type: string, body: Uint8Array): Uint8Array {
  const typed = concat(latin1(type), body);

  return concat(u32be(body.length), typed, u32be(crc32(typed)));
}

/** A zlib stream of one uncompressed deflate block. */
function zlibStored(data: Uint8Array): Uint8Array {
  return concat(
    Uint8Array.of(0x78, 0x01),
    Uint8Array.of(0x01),
    u16le(data.length),
    u16le(~data.length & 0xffff),
    data,
    u32be(adler32(data)),
  );
}

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;

  for (const byte of data) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) {
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }

  return (crc ^ 0xffffffff) >>> 0;
}

function adler32(data: Uint8Array): number {
  let low = 1;
  let high = 0;

  for (const byte of data) {
    low = (low + byte) % 65521;
    high = (high + low) % 65521;
  }

  return ((high << 16) | low) >>> 0;
}

/* --------------------------------------------------------------- bytes -- */

function concat(...parts: readonly Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const joined = new Uint8Array(total);
  let offset = 0;

  for (const part of parts) {
    joined.set(part, offset);
    offset += part.length;
  }

  return joined;
}

function latin1(text: string): Uint8Array {
  return Uint8Array.from(text, (character) => character.charCodeAt(0) & 0xff);
}

function utf8(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

function u16be(value: number): Uint8Array {
  return Uint8Array.of((value >> 8) & 0xff, value & 0xff);
}

function u24be(value: number): Uint8Array {
  return Uint8Array.of((value >> 16) & 0xff, (value >> 8) & 0xff, value & 0xff);
}

function u32be(value: number): Uint8Array {
  return Uint8Array.of(
    (value / 0x1000000) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 8) & 0xff,
    value & 0xff,
  );
}

function u16le(value: number): Uint8Array {
  return Uint8Array.of(value & 0xff, (value >> 8) & 0xff);
}

function u32le(value: number): Uint8Array {
  return Uint8Array.of(
    value & 0xff,
    (value >>> 8) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 24) & 0xff,
  );
}

function round(value: number, places = 0): number {
  const scale = 10 ** places;

  return Math.round(value * scale) / scale;
}
