/**
 * How the test fixtures are made.
 *
 * The committed files under this directory are assembled here, byte by byte,
 * from nothing but this module: an MP3 with an ID3v2.3 tag and an embedded
 * cover, a FLAC with a Vorbis comment block and a PICTURE block, two M4As that
 * differ only in whether `moov` comes before or after `mdat`, and an `.m3u`
 * that points at three of them plus a line that matches nothing.
 *
 * `pnpm --filter @stratosonic/server fixtures` writes what this module returns
 * to disk; a test calls the same functions and compares them with the committed
 * bytes, so the files can always be regenerated byte for byte. The generator
 * probes for `ffmpeg` and reports what it finds, but does not use it: an
 * encoder's output varies with its version and build, and these fixtures have
 * to be reproducible by anyone. Nothing here is a real encoding - the audio is
 * zeroes and the FLAC and MP4 frames are stubs. The files are parseable as
 * their container, which is all the metadata extractor and the scanner need;
 * they are not playable, and the MP4s carry no sample tables, so their (absent)
 * chunk offsets are meaningless.
 *
 * Every expectation these files carry - tags, durations, bit rates, cover
 * types, which playlist lines match - is written into `manifest.json` by the
 * same run, so the tests that read the fixtures never restate them.
 */

/** A file as it is committed under this directory. */
export interface FixtureFile {
  readonly name: string;
  readonly bytes: Uint8Array;
}

export type FixtureSuffix = "mp3" | "flac" | "m4a";

/** What a fixture's bytes say, for the tests that read them. */
export interface FixtureTrack {
  /** File name under `test/fixtures`. */
  readonly file: string;
  /** Where the seed helper puts it in the R2 bucket. */
  readonly r2Key: string;
  readonly size: number;
  readonly suffix: FixtureSuffix;
  readonly contentType: string;
  readonly container: {
    readonly tagFormat: "id3v2.3" | "vorbis-comment" | "mp4-ilst";
    /** MP4 only: whether the metadata sits at the front of the file. */
    readonly moovBeforeMdat?: boolean;
  };
  readonly tags: {
    readonly title: string;
    readonly artist: string;
    readonly albumArtist: string;
    readonly album: string;
    readonly trackNumber: number;
    readonly trackCount: number;
    readonly discNumber: number;
    readonly discCount: number;
    readonly year: number;
    readonly genre: string;
  };
  readonly duration: {
    readonly seconds: number;
    readonly toleranceSeconds: number;
    /** Which of the three rules in #9 yields it. */
    readonly source: "cbr-estimate" | "streaminfo" | "mvhd";
  };
  readonly bitRate: {
    readonly kbps: number;
    readonly source: "frame-header" | "size-and-duration";
  };
  readonly cover: {
    readonly mimeType: string;
    readonly size: number;
    readonly width: number;
    readonly height: number;
  } | null;
}

/** One line of the `.m3u`, and what the importer should make of it. */
export interface FixturePlaylistLine {
  readonly text: string;
  /** The R2 key the line resolves to, or null for a comment or blank line. */
  readonly resolvesTo: string | null;
  readonly matchesATrack: boolean;
}

export interface FixturePlaylist {
  readonly file: string;
  readonly r2Key: string;
  /** The playlist's name: the file name without its extension. */
  readonly name: string;
  readonly size: number;
  readonly lines: readonly FixturePlaylistLine[];
  /** The tracks it should import, in order. */
  readonly trackKeys: readonly string[];
  readonly unmatchedLineCount: number;
}

export interface FixturesManifest {
  readonly generator: {
    readonly command: string;
    readonly source: string;
    readonly engine: "programmatic";
  };
  readonly tracks: readonly FixtureTrack[];
  readonly playlist: FixturePlaylist;
}

/** Everything under this directory, and what it means. */
export interface BuiltFixtures {
  readonly files: readonly FixtureFile[];
  readonly manifest: FixturesManifest;
}

const COVER_WIDTH = 1;
const COVER_HEIGHT = 1;

/** MPEG-1 Layer III, 128 kbps, 44.1 kHz: the MP3 fixture's one frame shape. */
const MP3_BIT_RATE = 128;
const MP3_SAMPLE_RATE = 44_100;
const MP3_FRAME_SIZE = Math.floor((144 * MP3_BIT_RATE * 1000) / MP3_SAMPLE_RATE);
const MP3_FRAME_COUNT = 8;

const FLAC_SAMPLE_RATE = 44_100;
const FLAC_TOTAL_SAMPLES = 44_100;
const FLAC_STUB_FRAME_SIZE = 2048;

const MP4_TIMESCALE = 1000;
const MP4_DURATION_UNITS = 2500;
const MP4_MDAT_SIZE = 2048;

/** Builds every fixture file together with the manifest that describes them. */
export function buildFixtures(): BuiltFixtures {
  const cover = pngCover();

  const mp3 = mp3Fixture(cover);
  const flac = flacFixture(cover);
  const front = mp4Fixture({
    file: "front-loaded.m4a",
    r2Key: "Mute Ensemble/Faststart Sessions/01 Front Loaded.m4a",
    moovBeforeMdat: true,
    tags: {
      title: "Front Loaded",
      artist: "Mute Ensemble",
      albumArtist: "Mute Ensemble",
      album: "Faststart Sessions",
      trackNumber: 1,
      trackCount: 3,
      discNumber: 1,
      discCount: 1,
      year: 2019,
      genre: "Ambient",
    },
    cover,
  });
  const tail = mp4Fixture({
    file: "tail-loaded.m4a",
    r2Key: "Mute Ensemble/Trailing Sessions/01 Tail Loaded.m4a",
    moovBeforeMdat: false,
    tags: {
      title: "Tail Loaded",
      artist: "Mute Ensemble",
      albumArtist: "Mute Ensemble",
      album: "Trailing Sessions",
      trackNumber: 1,
      trackCount: 3,
      discNumber: 1,
      discCount: 1,
      year: 2019,
      genre: "Ambient",
    },
    cover,
  });

  const tracks = [mp3, flac, front, tail];
  const playlist = m3uFixture(tracks);

  return {
    files: [...tracks.map((track) => track.fixture), playlist.fixture],
    manifest: {
      generator: {
        command: "pnpm --filter @stratosonic/server fixtures",
        source: "apps/server/test/fixtures/build.ts",
        engine: "programmatic",
      },
      tracks: tracks.map((track) => track.track),
      playlist: playlist.playlist,
    },
  };
}

interface BuiltTrack {
  readonly fixture: FixtureFile;
  readonly track: FixtureTrack;
}

/* ------------------------------------------------------------------ MP3 -- */

function mp3Fixture(cover: Uint8Array): BuiltTrack {
  const tags = {
    title: "Silent Track",
    artist: "Silent Artist",
    albumArtist: "Silent Artist",
    album: "Quiet Album",
    trackNumber: 1,
    trackCount: 2,
    discNumber: 1,
    discCount: 1,
    year: 2001,
    genre: "Electronic",
  } as const;

  const frames = concat(
    id3TextFrame("TIT2", tags.title),
    id3TextFrame("TPE1", tags.artist),
    id3TextFrame("TPE2", tags.albumArtist),
    id3TextFrame("TALB", tags.album),
    id3TextFrame("TRCK", `${tags.trackNumber}/${tags.trackCount}`),
    id3TextFrame("TPOS", `${tags.discNumber}/${tags.discCount}`),
    id3TextFrame("TYER", String(tags.year)),
    id3TextFrame("TCON", tags.genre),
    id3Frame(
      "APIC",
      concat(
        Uint8Array.of(0x00),
        latin1("image/png"),
        Uint8Array.of(0x00),
        // Picture type 3: the front cover.
        Uint8Array.of(0x03),
        Uint8Array.of(0x00),
        cover,
      ),
    ),
  );

  // "ID3", version 2.3.0, no flags, then the tag size as a syncsafe integer.
  const header = concat(latin1("ID3"), Uint8Array.of(0x03, 0x00, 0x00), syncsafe(frames.length));

  // MPEG-1 Layer III, 128 kbps, 44.1 kHz, stereo, no padding. The frames carry
  // zeroes: nothing decodes them, and the duration comes from their count.
  const audio = new Uint8Array(MP3_FRAME_SIZE * MP3_FRAME_COUNT);
  for (let frame = 0; frame < MP3_FRAME_COUNT; frame++) {
    audio.set(Uint8Array.of(0xff, 0xfb, 0x90, 0x00), frame * MP3_FRAME_SIZE);
  }

  const bytes = concat(header, frames, audio);

  return {
    fixture: { name: "silent-track.mp3", bytes },
    track: {
      file: "silent-track.mp3",
      r2Key: "Silent Artist/Quiet Album/01 Silent Track.mp3",
      size: bytes.length,
      suffix: "mp3",
      contentType: "audio/mpeg",
      container: { tagFormat: "id3v2.3" },
      tags,
      duration: {
        // No Xing or Info frame, so the duration is the CBR estimate over the
        // audio bytes; it agrees with frames x 1152 / 44100 to a millisecond.
        seconds: round((audio.length * 8) / (MP3_BIT_RATE * 1000), 3),
        toleranceSeconds: 0.05,
        source: "cbr-estimate",
      },
      bitRate: { kbps: MP3_BIT_RATE, source: "frame-header" },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

/** An ID3v2.3 frame: id, size (plain big-endian in 2.3), two flag bytes. */
function id3Frame(id: string, body: Uint8Array): Uint8Array {
  return concat(latin1(id), u32be(body.length), Uint8Array.of(0x00, 0x00), body);
}

/** A text frame, in ISO-8859-1 as encoding byte 0 declares. */
function id3TextFrame(id: string, text: string): Uint8Array {
  return id3Frame(id, concat(Uint8Array.of(0x00), latin1(text)));
}

/** A 28-bit integer spread over four bytes, seven bits each. */
function syncsafe(value: number): Uint8Array {
  return Uint8Array.of(
    (value >> 21) & 0x7f,
    (value >> 14) & 0x7f,
    (value >> 7) & 0x7f,
    value & 0x7f,
  );
}

/* ----------------------------------------------------------------- FLAC -- */

function flacFixture(cover: Uint8Array): BuiltTrack {
  const tags = {
    title: "Hushed Interlude",
    // The track artist differs from the album artist on purpose: the library
    // groups by album artist, and something has to prove it.
    artist: "Silent Artist feat. Echo",
    albumArtist: "Silent Artist",
    album: "Quiet Album",
    trackNumber: 2,
    trackCount: 2,
    discNumber: 1,
    discCount: 1,
    year: 2001,
    genre: "Electronic",
  } as const;

  const streamInfo = new Uint8Array(34);
  const view = new DataView(streamInfo.buffer);
  // Minimum and maximum block size, then minimum and maximum frame size (both
  // zero, meaning "unknown").
  view.setUint16(0, 4096);
  view.setUint16(2, 4096);
  // Bits 20 (sample rate), 3 (channels - 1), 5 (bits per sample - 1) and 36
  // (total samples) are packed into the eight bytes from offset 10.
  const packed =
    (BigInt(FLAC_SAMPLE_RATE) << 44n) | (1n << 41n) | (15n << 36n) | BigInt(FLAC_TOTAL_SAMPLES);
  view.setBigUint64(10, packed);
  // The last 16 bytes are the MD5 of the unencoded audio, which may be zero
  // when it is unknown.

  const comments = [
    `TITLE=${tags.title}`,
    `ARTIST=${tags.artist}`,
    `ALBUMARTIST=${tags.albumArtist}`,
    `ALBUM=${tags.album}`,
    `TRACKNUMBER=${tags.trackNumber}`,
    `TRACKTOTAL=${tags.trackCount}`,
    `DISCNUMBER=${tags.discNumber}`,
    `DATE=${tags.year}`,
    `GENRE=${tags.genre}`,
  ];
  const vendor = utf8("stratosonic fixtures");
  const vorbisComment = concat(
    u32le(vendor.length),
    vendor,
    u32le(comments.length),
    ...comments.map((comment) => {
      const encoded = utf8(comment);
      return concat(u32le(encoded.length), encoded);
    }),
  );

  const mimeType = latin1("image/png");
  const description = utf8("front cover");
  const picture = concat(
    u32be(3),
    u32be(mimeType.length),
    mimeType,
    u32be(description.length),
    description,
    u32be(COVER_WIDTH),
    u32be(COVER_HEIGHT),
    // 24-bit colour, not a palette.
    u32be(24),
    u32be(0),
    u32be(cover.length),
    cover,
  );

  // A stub frame, so the file does not end on its metadata. It is not decodable
  // and nothing reads it: the duration comes from STREAMINFO.
  const frame = new Uint8Array(FLAC_STUB_FRAME_SIZE);
  frame.set(Uint8Array.of(0xff, 0xf8, 0x69, 0x18, 0x00));

  const bytes = concat(
    latin1("fLaC"),
    flacBlock(0, streamInfo, false),
    flacBlock(4, vorbisComment, false),
    flacBlock(6, picture, true),
    frame,
  );
  const seconds = FLAC_TOTAL_SAMPLES / FLAC_SAMPLE_RATE;

  return {
    fixture: { name: "hushed-interlude.flac", bytes },
    track: {
      file: "hushed-interlude.flac",
      r2Key: "Silent Artist/Quiet Album/02 Hushed Interlude.flac",
      size: bytes.length,
      suffix: "flac",
      contentType: "audio/flac",
      container: { tagFormat: "vorbis-comment" },
      tags,
      duration: { seconds, toleranceSeconds: 0.01, source: "streaminfo" },
      // FLAC states no bit rate, so it is the file's own: these bytes are not
      // a real encoding, so the number is small, but the rule is the rule.
      bitRate: { kbps: round((bytes.length * 8) / 1000 / seconds), source: "size-and-duration" },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

/** A metadata block: one byte of "last block" flag and type, then a 24-bit length. */
function flacBlock(type: number, body: Uint8Array, last: boolean): Uint8Array {
  return concat(Uint8Array.of((last ? 0x80 : 0x00) | type), u24be(body.length), body);
}

/* ------------------------------------------------------------------ MP4 -- */

interface Mp4Spec {
  readonly file: string;
  readonly r2Key: string;
  readonly moovBeforeMdat: boolean;
  readonly tags: FixtureTrack["tags"];
  readonly cover: Uint8Array;
}

function mp4Fixture(spec: Mp4Spec): BuiltTrack {
  const { tags, cover } = spec;

  const ftyp = atom(
    "ftyp",
    concat(latin1("M4A "), u32be(0x200), latin1("M4A "), latin1("mp42"), latin1("isom")),
  );

  const mvhd = atom(
    "mvhd",
    concat(
      // Version 0, no flags; created and modified at the epoch.
      u32be(0),
      u32be(0),
      u32be(0),
      u32be(MP4_TIMESCALE),
      u32be(MP4_DURATION_UNITS),
      // Rate 1.0, volume 1.0, then the reserved words, the unity matrix and
      // the predefined block, all as the specification fixes them.
      u32be(0x00010000),
      Uint8Array.of(0x01, 0x00),
      new Uint8Array(10),
      unityMatrix(),
      new Uint8Array(24),
      u32be(1),
    ),
  );

  const hdlr = atom(
    "hdlr",
    concat(u32be(0), u32be(0), latin1("mdir"), latin1("appl"), new Uint8Array(8)),
  );

  const ilst = atom(
    "ilst",
    concat(
      itunesText("\u00a9nam", tags.title),
      itunesText("\u00a9ART", tags.artist),
      itunesText("aART", tags.albumArtist),
      itunesText("\u00a9alb", tags.album),
      itunesText("\u00a9day", String(tags.year)),
      itunesText("\u00a9gen", tags.genre),
      itunesNumberPair("trkn", tags.trackNumber, tags.trackCount),
      itunesNumberPair("disk", tags.discNumber, tags.discCount),
      // Data type 14 says the picture is a PNG.
      itunesItem("covr", 14, cover),
    ),
  );

  // `meta` is a full box: four bytes of version and flags before its children.
  const meta = atom("meta", concat(u32be(0), hdlr, ilst));
  const moov = atom("moov", concat(mvhd, atom("udta", meta)));
  const mdat = atom("mdat", new Uint8Array(MP4_MDAT_SIZE));

  const bytes = spec.moovBeforeMdat ? concat(ftyp, moov, mdat) : concat(ftyp, mdat, moov);
  const seconds = MP4_DURATION_UNITS / MP4_TIMESCALE;

  return {
    fixture: { name: spec.file, bytes },
    track: {
      file: spec.file,
      r2Key: spec.r2Key,
      size: bytes.length,
      suffix: "m4a",
      contentType: "audio/mp4",
      container: { tagFormat: "mp4-ilst", moovBeforeMdat: spec.moovBeforeMdat },
      tags,
      duration: { seconds, toleranceSeconds: 0.01, source: "mvhd" },
      bitRate: { kbps: round((bytes.length * 8) / 1000 / seconds), source: "size-and-duration" },
      cover: {
        mimeType: "image/png",
        size: cover.length,
        width: COVER_WIDTH,
        height: COVER_HEIGHT,
      },
    },
  };
}

function atom(type: string, body: Uint8Array): Uint8Array {
  return concat(u32be(body.length + 8), latin1(type), body);
}

/** An `ilst` entry: a named atom wrapping one `data` atom. */
function itunesItem(name: string, dataType: number, value: Uint8Array): Uint8Array {
  return atom(name, atom("data", concat(u32be(dataType), u32be(0), value)));
}

/** Data type 1: UTF-8 text. */
function itunesText(name: string, text: string): Uint8Array {
  return itunesItem(name, 1, utf8(text));
}

/** Data type 0: `trkn` and `disk` hold their two numbers as binary. */
function itunesNumberPair(name: string, number: number, total: number): Uint8Array {
  return itunesItem(name, 0, concat(u16be(0), u16be(number), u16be(total), u16be(0)));
}

function unityMatrix(): Uint8Array {
  return concat(
    u32be(0x00010000),
    u32be(0),
    u32be(0),
    u32be(0),
    u32be(0x00010000),
    u32be(0),
    u32be(0),
    u32be(0),
    u32be(0x40000000),
  );
}

/* ------------------------------------------------------------------ m3u -- */

interface BuiltPlaylist {
  readonly fixture: FixtureFile;
  readonly playlist: FixturePlaylist;
}

function m3uFixture(tracks: readonly BuiltTrack[]): BuiltPlaylist {
  const [mp3, flac, front] = tracks;
  if (!mp3 || !flac || !front) {
    throw new Error("the playlist fixture needs the three tracks it lists");
  }

  const missing = "Missing Artist/Missing Album/Nowhere.mp3";

  // The playlist lives in a directory of its own, so a line has to be resolved
  // against `playlists/` before it names an R2 key. One line is relative, one
  // is absolute, one names a track that is not in the bucket, and the fourth
  // track in the fixtures is deliberately absent from the file.
  const lines: FixturePlaylistLine[] = [
    { text: "#EXTM3U", resolvesTo: null, matchesATrack: false },
    {
      text: `#EXTINF:1,${mp3.track.tags.artist} - ${mp3.track.tags.title}`,
      resolvesTo: null,
      matchesATrack: false,
    },
    { text: `../${mp3.track.r2Key}`, resolvesTo: mp3.track.r2Key, matchesATrack: true },
    { text: `/${front.track.r2Key}`, resolvesTo: front.track.r2Key, matchesATrack: true },
    { text: "", resolvesTo: null, matchesATrack: false },
    { text: `../${missing}`, resolvesTo: missing, matchesATrack: false },
    { text: `../${flac.track.r2Key}`, resolvesTo: flac.track.r2Key, matchesATrack: true },
  ];

  const bytes = utf8(`${lines.map((line) => line.text).join("\n")}\n`);

  return {
    fixture: { name: "favourites.m3u", bytes },
    playlist: {
      file: "favourites.m3u",
      r2Key: "playlists/favourites.m3u",
      name: "favourites",
      size: bytes.length,
      lines,
      trackKeys: lines
        .filter((line) => line.matchesATrack)
        .map((line) => line.resolvesTo as string),
      unmatchedLineCount: 1,
    },
  };
}

/* ---------------------------------------------------------------- cover -- */

/**
 * A one-pixel PNG. It is built rather than pasted in so its checksums are right
 * by construction: the image is small but real, and the cover path treats it as
 * it would any other.
 */
function pngCover(): Uint8Array {
  const ihdr = concat(
    u32be(COVER_WIDTH),
    u32be(COVER_HEIGHT),
    // Eight bits per sample, colour type 2 (RGB), no compression, filter or
    // interlacing beyond the defaults.
    Uint8Array.of(8, 2, 0, 0, 0),
  );
  // One scanline: the filter byte, then one grey pixel.
  const raw = Uint8Array.of(0x00, 0x30, 0x30, 0x30);

  return concat(
    Uint8Array.of(0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", zlibStored(raw)),
    pngChunk("IEND", new Uint8Array(0)),
  );
}

function pngChunk(type: string, body: Uint8Array): Uint8Array {
  const typed = concat(latin1(type), body);

  return concat(u32be(body.length), typed, u32be(crc32(typed)));
}

/** A zlib stream of one uncompressed deflate block. */
function zlibStored(data: Uint8Array): Uint8Array {
  return concat(
    Uint8Array.of(0x78, 0x01),
    Uint8Array.of(0x01),
    u16le(data.length),
    u16le(~data.length & 0xffff),
    data,
    u32be(adler32(data)),
  );
}

function crc32(data: Uint8Array): number {
  let crc = 0xffffffff;

  for (const byte of data) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) {
      crc = crc & 1 ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }

  return (crc ^ 0xffffffff) >>> 0;
}

function adler32(data: Uint8Array): number {
  let low = 1;
  let high = 0;

  for (const byte of data) {
    low = (low + byte) % 65521;
    high = (high + low) % 65521;
  }

  return ((high << 16) | low) >>> 0;
}

/* --------------------------------------------------------------- bytes -- */

function concat(...parts: readonly Uint8Array[]): Uint8Array {
  const total = parts.reduce((sum, part) => sum + part.length, 0);
  const joined = new Uint8Array(total);
  let offset = 0;

  for (const part of parts) {
    joined.set(part, offset);
    offset += part.length;
  }

  return joined;
}

function latin1(text: string): Uint8Array {
  return Uint8Array.from(text, (character) => character.charCodeAt(0) & 0xff);
}

function utf8(text: string): Uint8Array {
  return new TextEncoder().encode(text);
}

function u16be(value: number): Uint8Array {
  return Uint8Array.of((value >> 8) & 0xff, value & 0xff);
}

function u24be(value: number): Uint8Array {
  return Uint8Array.of((value >> 16) & 0xff, (value >> 8) & 0xff, value & 0xff);
}

function u32be(value: number): Uint8Array {
  return Uint8Array.of(
    (value >>> 24) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 8) & 0xff,
    value & 0xff,
  );
}

function u16le(value: number): Uint8Array {
  return Uint8Array.of(value & 0xff, (value >> 8) & 0xff);
}

function u32le(value: number): Uint8Array {
  return Uint8Array.of(
    value & 0xff,
    (value >>> 8) & 0xff,
    (value >>> 16) & 0xff,
    (value >>> 24) & 0xff,
  );
}

function round(value: number, places = 0): number {
  const scale = 10 ** places;

  return Math.round(value * scale) / scale;
}
