/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false` (hash: bd6e0f32d1d2c41e9ca4690145281dbd)
interface __BaseEnv_Env {
	MUSIC: R2Bucket;
	DB: D1Database;
	INITIAL_USER: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface PreviewEnv {
		MUSIC: R2Bucket;
		DB: D1Database;
		INITIAL_USER: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INITIAL_USER">> {}
}
