/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=/dev/null --include-runtime=false --strict-vars=false` (hash: 1692b7568f580c7fa421008675a29d90)
interface __BaseEnv_Env {
	MUSIC: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	INITIAL_USER: string;
	FILE_WRITES?: string;
	SCAN_DRIVER: DurableObjectNamespace<import("./src/index").ScanDriver>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ScanDriver";
	}
	interface PreviewEnv {
		MUSIC: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		INITIAL_USER: string;
		FILE_WRITES: string;
		SCAN_DRIVER: DurableObjectNamespace<import("./src/index").ScanDriver>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INITIAL_USER" | "FILE_WRITES">> {}
}
